### ISSUE TITLE
Not an Issue But a quick question

### ISSUE THREAD

**Issue by redskates** [greg-js/arch-wiki-man#1]
Where are arch-wiki-man pages stored? I'm wondering if I can pipe a search into a markdown editor.  And, thanks, this is a great application!

**Comment by greg-js** [comment]
Thanks for the kind words. They're stored wherever your global node packages are so it's different depending on whether you've installed node normally or through nvm or something. Check `which node` and they should be in `../../lib/node_modules` of that. There should be an `arch-wiki-man` folder there, and in there, check `node_modules/arch-wiki-md-repo`.

Alternatively, you can just `npm install --save arch-wiki-md-repo` in your own node program and get access to the whole local wiki directly (in markdown but it's not 100% true to the original html, like I filter out a bunch of divs and links that aren't relevant on the command line)
